[package]
name = "webimage"
version = "0.1.0"
edition = "2018"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
image = "0.23"
rayon = "1.5"
structopt = "0.3"

[profile.release]
lto = true
codegen-units = 1
